Refactoring
DANS-KNAW/gmh-registration-service pull request #4
Opened 2021-02-03 11:42 UTC by ChrisMuller80

2021-02-03 15:45 UTC, wilkos-dans reviewed
* Kunnen onze eigen implementatie classes niet in een package met een andere naam? Ik mis iets van: nl.knaw.dans.nbnresover?
 * Ik mis de swagger-ui files onder de webapp.

2021-02-03 15:45 UTC, wilkos-dans commented on openapi.yaml
> +openapi: 3.0.3
Deze file verwacht ik niet in de root?!

2021-02-05 12:27 UTC, ChrisMuller80 commented
>     * Kunnen onze eigen implementatie classes niet in een package met een andere naam? Ik mis iets van: nl.knaw.dans.nbnresover?
> 
>     * Ik mis de swagger-ui files onder de webapp.

Done

2021-03-04 11:40 UTC, wilkos-dans requested changes
Hi,
Please notice:
- I updated the POM, to include DANS parent POM now.
- I am missing the src/main/resources folder? (`Caused by: java.util.MissingResourceException: Can't find bundle for base name application, locale en_N`L)
- I am missing a unit test.

2021-03-10 15:09 UTC, ChrisMuller80 commented
> Hi,
> Please notice:
> 
>     * I updated the POM, to include DANS parent POM now.
> 
>     * I am missing the src/main/resources folder? (`Caused by: java.util.MissingResourceException: Can't find bundle for base name application, locale en_N`L)
> 
I changed this. The resource bundle was not needed.
>     * I am missing a unit test.

2021-04-07 10:04 UTC, wilkos-dans commented
Still in Draft/WIP?

2021-04-07 15:03 UTC, wilkos-dans approved these changes

2021-04-07 15:08 UTC, wilkos-dans commented
Looks good.
One more comment for now: If the DB (connection) is missing/DB stops, (almost?) all the API calls return this json:
```
{
  "code": 401,
  "message": "Authentication information is missing or invalid"
}
```
Which is not correct, or at least does not reveal the 'real' problem.

2021-04-07 15:11 UTC, merged